// Auto-generated CVP repro. Build: rustc -O -Ccodegen-units=1 this.rs --crate-type=lib
#![allow(dead_code)]

#[inline(never)]
pub fn make_one(x: u64) -> Result<String, ()> {
    if x == u64::MAX { Err(()) } else { Ok(x.to_string()) }
}

pub struct Big {
    f0: String,
    f1: String,
    f2: String,
    f3: String,
    f4: String,
    f5: String,
    f6: String,
    f7: String,
    f8: String,
    f9: String,
    f10: String,
    f11: String,
    f12: String,
    f13: String,
    f14: String,
    f15: String,
    f16: String,
    f17: String,
    f18: String,
    f19: String,
    f20: String,
    f21: String,
    f22: String,
    f23: String,
    f24: String,
    f25: String,
    f26: String,
    f27: String,
    f28: String,
    f29: String,
    f30: String,
    f31: String,
    f32: String,
    f33: String,
    f34: String,
    f35: String,
    f36: String,
    f37: String,
    f38: String,
    f39: String,
    f40: String,
    f41: String,
    f42: String,
    f43: String,
    f44: String,
    f45: String,
    f46: String,
    f47: String,
    f48: String,
    f49: String,
    f50: String,
    f51: String,
    f52: String,
    f53: String,
    f54: String,
    f55: String,
    f56: String,
    f57: String,
    f58: String,
    f59: String,
    f60: String,
    f61: String,
    f62: String,
    f63: String,
}

#[inline(never)]
pub fn build(seed: u64) -> Result<Big, ()> {
    Ok(Big {
        f0: make_one(seed ^ 0)?,
        f1: make_one(seed ^ 1)?,
        f2: make_one(seed ^ 2)?,
        f3: make_one(seed ^ 3)?,
        f4: make_one(seed ^ 4)?,
        f5: make_one(seed ^ 5)?,
        f6: make_one(seed ^ 6)?,
        f7: make_one(seed ^ 7)?,
        f8: make_one(seed ^ 8)?,
        f9: make_one(seed ^ 9)?,
        f10: make_one(seed ^ 10)?,
        f11: make_one(seed ^ 11)?,
        f12: make_one(seed ^ 12)?,
        f13: make_one(seed ^ 13)?,
        f14: make_one(seed ^ 14)?,
        f15: make_one(seed ^ 15)?,
        f16: make_one(seed ^ 16)?,
        f17: make_one(seed ^ 17)?,
        f18: make_one(seed ^ 18)?,
        f19: make_one(seed ^ 19)?,
        f20: make_one(seed ^ 20)?,
        f21: make_one(seed ^ 21)?,
        f22: make_one(seed ^ 22)?,
        f23: make_one(seed ^ 23)?,
        f24: make_one(seed ^ 24)?,
        f25: make_one(seed ^ 25)?,
        f26: make_one(seed ^ 26)?,
        f27: make_one(seed ^ 27)?,
        f28: make_one(seed ^ 28)?,
        f29: make_one(seed ^ 29)?,
        f30: make_one(seed ^ 30)?,
        f31: make_one(seed ^ 31)?,
        f32: make_one(seed ^ 32)?,
        f33: make_one(seed ^ 33)?,
        f34: make_one(seed ^ 34)?,
        f35: make_one(seed ^ 35)?,
        f36: make_one(seed ^ 36)?,
        f37: make_one(seed ^ 37)?,
        f38: make_one(seed ^ 38)?,
        f39: make_one(seed ^ 39)?,
        f40: make_one(seed ^ 40)?,
        f41: make_one(seed ^ 41)?,
        f42: make_one(seed ^ 42)?,
        f43: make_one(seed ^ 43)?,
        f44: make_one(seed ^ 44)?,
        f45: make_one(seed ^ 45)?,
        f46: make_one(seed ^ 46)?,
        f47: make_one(seed ^ 47)?,
        f48: make_one(seed ^ 48)?,
        f49: make_one(seed ^ 49)?,
        f50: make_one(seed ^ 50)?,
        f51: make_one(seed ^ 51)?,
        f52: make_one(seed ^ 52)?,
        f53: make_one(seed ^ 53)?,
        f54: make_one(seed ^ 54)?,
        f55: make_one(seed ^ 55)?,
        f56: make_one(seed ^ 56)?,
        f57: make_one(seed ^ 57)?,
        f58: make_one(seed ^ 58)?,
        f59: make_one(seed ^ 59)?,
        f60: make_one(seed ^ 60)?,
        f61: make_one(seed ^ 61)?,
        f62: make_one(seed ^ 62)?,
        f63: make_one(seed ^ 63)?,
    })
}
